import { test,expect,type BrowserContext,type Page } from '@playwright/test';
import { Pool } from 'pg';
import { randomUUID,randomBytes,createHash } from 'node:crypto';
import sharp from 'sharp';
if(process.env.BIOSFERA_E2E!=='1')throw new Error('Use npm run test:e2e.');
const pool=new Pool({connectionString:process.env.DATABASE_URL});
test.afterAll(async()=>{await pool.query("DELETE FROM users WHERE email IN ('admin4@example.test','editor4@example.test')");await pool.query('DELETE FROM sessions');await pool.query("DELETE FROM ad_campaigns WHERE name='Campanha Fase 4'");await pool.end();});test.setTimeout(120000);
const password='Teste seguro fase quatro 123!';
async function auth(context:BrowserContext,id?:string){const user=id?{id}:(await pool.query("SELECT id FROM users WHERE role='OWNER' AND active LIMIT 1")).rows[0];const token=randomBytes(32).toString('hex');await pool.query("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '1 hour')",[randomUUID(),user.id,createHash('sha256').update(token).digest('hex')]);await context.addCookies([{name:'__Host-biosfera_session',value:token,domain:'localhost',path:'/',secure:true,httpOnly:true,sameSite:'Lax'}]);return user.id;}
async function createUser(page:Page,email:string,role:string){await page.goto('/admin/usuarios/novo');await page.getByLabel('Nome',{exact:true}).fill('Equipe Fase 4');await page.getByLabel('E-mail',{exact:true}).fill(email);await page.getByLabel('Papel',{exact:true}).selectOption(role);await page.getByLabel('Senha inicial',{exact:true}).fill(password);await page.getByLabel('Confirmar senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Salvar',exact:true}).click();}
test('usuários: criação, privilégios, último OWNER, sessões, reset e Minha Conta',async({page,context,browser})=>{
 const owner=await auth(context);
 await createUser(page,'admin4@example.test','ADMIN');await expect(page).toHaveURL(/\/admin\/usuarios$/);
 await createUser(page,'editor4@example.test','EDITOR');await expect(page).toHaveURL(/\/admin\/usuarios$/);
 const admin=(await pool.query("SELECT id,password_hash FROM users WHERE email='admin4@example.test'")).rows[0];const editor=(await pool.query("SELECT id FROM users WHERE email='editor4@example.test'")).rows[0];expect(admin.password_hash).not.toBe(password);expect(admin.password_hash).toMatch(/^scrypt\$/);
 await createUser(page,'ADMIN4@example.test','ADMIN');await expect(page.locator('.admin-main').getByRole('status')).toContainText('e-mail já está cadastrado');
 await page.goto(`/admin/usuarios/${owner}`);await page.getByLabel('Ativo',{exact:true}).uncheck();await page.getByRole('button',{name:'Salvar',exact:true}).click();await expect(page.locator('.admin-main').getByRole('status')).toContainText('último OWNER');
 await page.getByLabel('Ativo',{exact:true}).check();await page.getByLabel('Papel',{exact:true}).selectOption('ADMIN');await page.getByRole('button',{name:'Salvar',exact:true}).click();await expect(page.locator('.admin-main').getByRole('status')).toContainText('último OWNER');
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Excluir usuário'}).click();await expect(page.locator('.admin-main').getByRole('status')).toContainText('último OWNER');
 const ac=await browser.newContext();await auth(ac,admin.id);const ap=await ac.newPage();await ap.goto(`/admin/usuarios/${owner}`);await expect(ap).toHaveURL(/\/admin\/usuarios$/);await ap.goto('/admin/usuarios/novo');
 await ap.getByLabel('Nome',{exact:true}).fill('Tentativa');await ap.getByLabel('E-mail',{exact:true}).fill('invalid-owner@example.test');await ap.getByLabel('Papel',{exact:true}).evaluate(el=>{const option=document.createElement('option');option.value='OWNER';option.text='OWNER';el.append(option);});await ap.getByLabel('Papel',{exact:true}).selectOption('OWNER');await ap.getByLabel('Senha inicial',{exact:true}).fill(password);await ap.getByLabel('Confirmar senha',{exact:true}).fill(password);await ap.getByRole('button',{name:'Salvar',exact:true}).click();await expect(ap.locator('.admin-main').getByRole('status')).toContainText('permissão');
 // Forge a reset target after opening a permitted form: backend must protect OWNER.
 await ap.goto(`/admin/usuarios/${editor.id}`);await ap.getByText('Redefinir senha',{exact:true}).first().click();const reset=ap.locator('details form');await reset.locator('[name="id"]').evaluate((el,id)=>(el as HTMLInputElement).value=id,owner);await reset.getByLabel('Nova senha',{exact:true}).fill(password);await reset.getByLabel('Confirmar senha',{exact:true}).fill(password);await reset.getByRole('button',{name:'Redefinir senha',exact:true}).click();await expect(ap.locator('.admin-main').getByRole('status')).toContainText('permissão');
 const ec=await browser.newContext();await auth(ec,editor.id);const ep=await ec.newPage();for(const route of ['/admin/usuarios','/admin/publicidade','/admin/configuracoes']){await ep.goto(route);await expect(ep).toHaveURL(/\/admin$/);}
 await page.goto(`/admin/usuarios/${editor.id}`);await page.getByLabel('Ativo',{exact:true}).uncheck();await page.getByRole('button',{name:'Salvar',exact:true}).click();await expect(page).toHaveURL(/\/admin\/usuarios$/);expect((await pool.query('SELECT id FROM sessions WHERE user_id=$1',[editor.id])).rowCount).toBe(0);
 await ep.goto('/admin');await expect(ep).toHaveURL(/\/admin\/login$/);await ep.getByLabel('E-mail',{exact:true}).fill('editor4@example.test');await ep.getByLabel('Senha',{exact:true}).fill(password);await ep.getByRole('button',{name:'Entrar no painel'}).click();await expect(ep.locator('.form-error')).toContainText('inválidos');
 await page.goto(`/admin/usuarios/${editor.id}`);await page.getByLabel('Ativo',{exact:true}).check();await page.getByRole('button',{name:'Salvar',exact:true}).click();await expect(page).toHaveURL(/\/admin\/usuarios$/);await auth(ec,editor.id);
 await page.goto(`/admin/usuarios/${editor.id}`);await page.locator('summary').filter({hasText:'Redefinir senha'}).click();const rf=page.locator('details form');await rf.getByLabel('Nova senha',{exact:true}).fill(password+' nova');await rf.getByLabel('Confirmar senha',{exact:true}).fill(password+' nova');await rf.getByRole('button',{name:'Redefinir senha'}).click();await expect(page).toHaveURL(/\/admin\/usuarios$/);expect((await pool.query('SELECT id FROM sessions WHERE user_id=$1',[editor.id])).rowCount).toBe(0);
 await ep.goto('/admin/login');await ep.getByLabel('E-mail',{exact:true}).fill('editor4@example.test');await ep.getByLabel('Senha',{exact:true}).fill(password+' nova');await ep.getByRole('button',{name:'Entrar no painel'}).click();await expect(ep).toHaveURL(/\/admin$/);
 await ep.goto('/admin/minha-conta');await ep.getByLabel('Nome',{exact:true}).fill('Nome alterado');await ep.getByRole('button',{name:'Salvar',exact:true}).click();await expect(ep.locator('.admin-main').getByRole('status')).toContainText('salvas');expect((await pool.query('SELECT role FROM users WHERE id=$1',[editor.id])).rows[0].role).toBe('EDITOR');
 await ep.locator('.phase-form').first().evaluate(form=>{const input=document.createElement('input');input.type='hidden';input.name='role';input.value='OWNER';form.append(input);});await ep.getByRole('button',{name:'Salvar',exact:true}).click();await expect(ep.locator('.admin-main').getByRole('status')).toContainText('apenas nome e senha');await ep.locator('[name="role"]').evaluate(el=>el.remove());
 await ep.locator('summary').click();const own=ep.locator('details form');await own.getByLabel('Senha atual',{exact:true}).fill(password+' nova');await own.getByLabel('Nova senha',{exact:true}).fill(password+' final');await own.getByLabel('Confirmar senha',{exact:true}).fill(password+' final');await own.getByRole('button',{name:'Trocar senha',exact:true}).click();await expect(ep).toHaveURL(/\/admin\/login$/);expect((await pool.query('SELECT id FROM sessions WHERE user_id=$1',[editor.id])).rowCount).toBe(0);
 const audits=(await pool.query("SELECT metadata::text FROM audit_log WHERE action LIKE 'users.%'")).rows.map(r=>r.metadata).join('');expect(audits).not.toContain(password);expect(audits).not.toContain('scrypt');
 for(const route of ['/admin/usuarios','/admin/usuarios/novo','/admin/minha-conta','/admin/configuracoes']){await page.goto(route);await page.screenshot({path:`test-results/phase4-${route.replaceAll('/','-')}.png`,fullPage:true});}
 await ac.close();await ec.close();
});
test('configurações: OWNER valida fuso e URL e salva somente opções operacionais',async({page,context})=>{
 await auth(context);await page.goto('/admin/configuracoes');const site=await page.getByLabel('Nome do portal',{exact:true}).inputValue();
 await page.getByLabel('Fuso horário do portal',{exact:true}).fill('Fuso/Inexistente');await page.getByRole('button',{name:'Salvar configurações'}).click();await expect(page.locator('.admin-main').getByRole('status')).toContainText('Fuso horário inválido');
 await page.getByLabel('Fuso horário do portal',{exact:true}).fill('America/Sao_Paulo');await page.getByLabel('URL da transmissão de rádio',{exact:true}).fill('javascript:alert(1)');await page.getByRole('button',{name:'Salvar configurações'}).click();await expect(page.locator('.admin-main').getByRole('status')).toContainText('HTTPS');
 await page.reload();await page.getByLabel('Nome do portal',{exact:true}).fill('Biosfera configuração teste');await page.getByRole('button',{name:'Salvar configurações'}).click();await expect(page.locator('.admin-main').getByRole('status')).toContainText('salvas');expect((await pool.query("SELECT value FROM settings WHERE key='SITE_NAME'")).rows[0].value).toBe('Biosfera configuração teste');
 await page.getByLabel('Nome do portal',{exact:true}).fill(site);await page.getByRole('button',{name:'Salvar configurações'}).click();await expect(page.locator('.admin-main').getByRole('status')).toContainText('salvas');
});
test('publicidade: ADMIN cadastra, upload, veiculação, visibilidade, métricas, URLs e bloqueio EDITOR',async({page,context,browser})=>{
 await auth(context);for(const [email,role] of [['admin4@example.test','ADMIN'],['editor4@example.test','EDITOR']]){if(!(await pool.query('SELECT id FROM users WHERE email=$1',[email])).rowCount){await createUser(page,email,role);await expect(page).toHaveURL(/\/admin\/usuarios$/);}}
 const admin=(await pool.query("SELECT id FROM users WHERE email='admin4@example.test'")).rows[0];await auth(context,admin.id);
 const image=await sharp({create:{width:960,height:180,channels:3,background:'#185a41'}}).png().toBuffer();
 await page.goto('/admin/publicidade/nova');await page.getByLabel('Nome interno',{exact:true}).fill('Campanha Fase 4');await page.getByLabel('Anunciante',{exact:true}).fill('Anunciante de teste');const slot=(await pool.query("SELECT id FROM ad_slots WHERE code='HOME_BETWEEN_SECTIONS'")).rows[0];await page.getByLabel('Posição',{exact:true}).selectOption(slot.id);await page.getByLabel('Imagem principal',{exact:true}).setInputFiles({name:'banner.png',mimeType:'image/png',buffer:image});await expect(page.locator('.upload-preview')).toBeVisible();await page.getByLabel('Texto alternativo',{exact:true}).fill('Banner de teste');await page.getByLabel('URL de destino',{exact:true}).fill('https://example.org/oferta');await page.getByLabel('Início',{exact:true}).fill('2020-01-01T12:00');await page.getByLabel('Término (opcional)',{exact:true}).fill('2019-01-01T12:00');await page.getByRole('button',{name:'Salvar campanha'}).click();await expect(page.locator('.admin-main').getByRole('alert')).toContainText('posterior');
 // Reopen the form to verify a new campaign can be saved after invalid input.
 await page.reload();await page.getByLabel('Nome interno',{exact:true}).fill('Campanha Fase 4');await page.getByLabel('Anunciante',{exact:true}).fill('Anunciante de teste');await page.getByLabel('Posição',{exact:true}).selectOption(slot.id);await page.getByLabel('Imagem principal',{exact:true}).setInputFiles({name:'banner.png',mimeType:'image/png',buffer:image});await expect(page.locator('.upload-preview')).toBeVisible();await page.getByLabel('Texto alternativo',{exact:true}).fill('Banner de teste');await page.getByLabel('URL de destino',{exact:true}).fill('https://example.org/oferta');await page.getByLabel('Início',{exact:true}).fill('2020-01-01T12:00');await page.getByRole('button',{name:'Salvar campanha'}).click();await expect(page).toHaveURL(/\/admin\/publicidade$/);
 const campaign=(await pool.query("SELECT * FROM ad_campaigns WHERE name='Campanha Fase 4'")).rows[0];const serve=()=>context.request.get('/api/ads/serve?slot=HOME_BETWEEN_SECTIONS').then(r=>r.json());expect((await serve()).id).toBe(campaign.id);expect((await pool.query('SELECT impressions FROM ad_campaigns WHERE id=$1',[campaign.id])).rows[0].impressions).toBe('0');expect(await (await context.request.get('/api/ads/serve?slot=NEWS_TOP')).json()).toBe(null);
 await page.goto('/');const banner=page.locator('.ad-banner[data-slot="HOME_BETWEEN_SECTIONS"]');await expect(banner).toBeVisible();await banner.scrollIntoViewIfNeeded();await expect.poll(async()=>Number((await pool.query('SELECT impressions FROM ad_campaigns WHERE id=$1',[campaign.id])).rows[0].impressions)).toBe(1);
 const click=(await banner.locator('a').getAttribute('href'))!;const receipt=new URL(click,'http://localhost:3100').searchParams.get('receipt');for(let i=0;i<2;i++){const r=await context.request.get(click,{maxRedirects:0});expect(r.status()).toBe(302);expect(r.headers().location).toBe('https://example.org/oferta');await context.request.post('/api/ads/impression',{headers:{origin:'http://localhost:3100'},data:{id:campaign.id,receipt}});}const counts=(await pool.query('SELECT impressions,clicks FROM ad_campaigns WHERE id=$1',[campaign.id])).rows[0];expect(counts).toEqual({impressions:'1',clicks:'1'});
 await page.screenshot({path:'test-results/phase4-home-ad.png',fullPage:true});
 for(const sql of ["active=false","active=true,start_at=now()+interval '1 day'","start_at=now()-interval '2 days',end_at=now()-interval '1 day'"]){await pool.query(`UPDATE ad_campaigns SET ${sql} WHERE id=$1`,[campaign.id]);expect(await serve()).toBe(null);}expect((await context.request.get(click,{maxRedirects:0})).status()).toBe(404);
 await pool.query('UPDATE ad_campaigns SET active=true,start_at=$1,end_at=NULL WHERE id=$2',['2020-01-01',campaign.id]);await page.goto(`/admin/publicidade/${campaign.id}`);await page.getByLabel('URL de destino',{exact:true}).evaluate(el=>el.setAttribute('type','text'));await page.getByLabel('URL de destino',{exact:true}).fill('javascript:alert(1)');await page.getByRole('button',{name:'Salvar campanha'}).click();await expect(page.locator('.admin-main').getByRole('alert')).toContainText('HTTP');
 const ec=await browser.newContext();const editor=(await pool.query("SELECT id FROM users WHERE email='editor4@example.test'")).rows[0];await auth(ec,editor.id);const ep=await ec.newPage();await ep.goto('/admin/publicidade');await expect(ep).toHaveURL(/\/admin$/);expect((await ec.request.post('/api/ads/upload',{headers:{origin:'http://localhost:3100','content-type':'image/png','x-file-name':'banner.png'},data:image})).status()).toBe(403);await ec.close();
 await page.goto('/admin/publicidade');await expect(page.getByRole('cell',{name:'100.00%',exact:true})).toBeVisible();await page.screenshot({path:'test-results/phase4-publicidade.png',fullPage:true});
 const newsSlot=(await pool.query("SELECT id FROM ad_slots WHERE code='NEWS_TOP'")).rows[0];await pool.query('UPDATE ad_campaigns SET slot_id=$1 WHERE id=$2',[newsSlot.id,campaign.id]);
 const author=randomUUID(),article=randomUUID();await pool.query("INSERT INTO authors(id,name,slug) VALUES($1,'Autor teste banner','autor-banner-4')",[author]);await pool.query("INSERT INTO news(id,title,slug,body,author_id,status,published_at) VALUES($1,'Matéria com publicidade','materia-banner-4','Conteúdo editorial preservado. Publicidade aparece em posição controlada.',$2,'PUBLISHED',now())",[article,author]);
 await page.goto('/noticias/materia-banner-4');await expect(page.locator('.ad-banner[data-slot="NEWS_TOP"]')).toBeVisible();await expect(page.locator('.article-body')).toContainText('Conteúdo editorial preservado');await page.screenshot({path:'test-results/phase4-noticia-ad.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/phase4-noticia-mobile.png',fullPage:true});
 await pool.query('DELETE FROM news WHERE id=$1',[article]);await pool.query('DELETE FROM authors WHERE id=$1',[author]);
 await pool.query('UPDATE ad_campaigns SET active=false WHERE id=$1',[campaign.id]);await page.goto('/');await expect(page.locator('.ad-banner')).toHaveCount(0);
});
