'use client';
import { useCallback,useEffect,useId,useState } from 'react';
type Message={id:string;display_name:string;message:string;sender_type:string;status:string;visitor_id?:string;blocked?:boolean};
type State={enabled:boolean;visitor:{name:string;blocked:boolean}|null;messages:Message[]};
export function Chat({admin=false}:{admin?:boolean}){
 const attachmentHelp=useId();
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[before,setBefore]=useState('');
 const refresh=useCallback(async()=>{const r=await fetch('/api/chat'+(admin?'?admin=1&before='+before:''),{cache:'no-store'});const result=await r.json();if(!r.ok)throw new Error(result.error);setData(result);},[admin,before]);
 useEffect(()=>{let stopped=false;let timer:ReturnType<typeof setTimeout>;async function poll(){if(!document.hidden)try{await refresh();}catch(e){if(!stopped)setError((e as Error).message);}if(!stopped)timer=setTimeout(poll,5000);}void poll();return ()=>{stopped=true;clearTimeout(timer);};},[refresh]);
 async function action(intent:string,extra:Record<string,unknown>={}){setBusy(true);setError('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intent,...extra})});const result=await r.json();if(!r.ok)throw new Error(result.error);await refresh();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 return <section className={admin?'chat-admin':'chat-panel'} aria-label="Chat ao vivo"><div className="panel-heading"><h2>Chat ao vivo</h2><span className="eyebrow">{admin?'MODERAÇÃO':'PARTICIPE'}</span></div>
 {admin&&data&&<div className="phase-buttons"><button disabled={busy} onClick={()=>action(data.enabled?'disable':'enable')}>{data.enabled?'Desativar chat':'Ativar chat'}</button><button onClick={()=>setBefore('')}>Mensagens recentes</button>{data.messages.length>0&&<button onClick={()=>setBefore(data.messages[0].id)}>Mensagens anteriores</button>}</div>}
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Carregando conversa…</p>}{data&&!data.enabled&&<p>Chat temporariamente indisponível.</p>}
 {data&&(data.enabled||admin)&&<><ol className="chat-messages" aria-label="Mensagens recentes" aria-live="polite">{data.messages.map(m=><li key={m.id} className={m.sender_type==='STAFF'?'staff-message':''}><strong>{m.display_name}</strong><small className="chat-sender-label">{m.sender_type==='STAFF'?' · EQUIPE':' · OUVINTE'}</small><p>{m.message}</p>{admin&&<><small>{m.status}</small><div className="phase-buttons">{m.status!=='DELETED'&&<><button disabled={busy} onClick={()=>action(m.status==='HIDDEN'?'show':'hide',{id:m.id})}>{m.status==='HIDDEN'?'Exibir':'Ocultar'}</button><button disabled={busy} onClick={()=>{if(confirm('Excluir logicamente esta mensagem?'))void action('delete',{id:m.id});}}>Excluir</button></>}{m.visitor_id&&<button disabled={busy} onClick={()=>action(m.blocked?'unblock':'block',{id:m.visitor_id})}>{m.blocked?'Desbloquear':'Bloquear sessão'}</button>}</div></>}</li>)}</ol>
 {!data.messages.length&&<p>A conversa começa com você.</p>}
 {data.enabled&&(admin||data.visitor)?data.visitor?.blocked&&!admin?<p>Esta sessão está bloqueada para envio.</p>:<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const message=String(new FormData(form).get('message')||'');if(await action(admin?'reply':'send',{message}))form.reset();}}><label>{admin?'Resposta da Biosfera':'Sua mensagem'}<textarea name="message" required maxLength={500} placeholder="Digite sua mensagem..."/></label><div className="chat-send-actions">{!admin&&<div className="chat-attachments" role="group" aria-label="Anexos indisponíveis" aria-describedby={attachmentHelp}><button type="button" disabled aria-label="Enviar foto — em breve"><span aria-hidden="true">▧</span> Foto</button><button type="button" disabled aria-label="Enviar vídeo — em breve"><span aria-hidden="true">▷</span> Vídeo</button></div>}<button className="button" disabled={busy}>Enviar</button></div>{!admin&&<small id={attachmentHelp} className="chat-attachment-note">Fotos e vídeos em breve. Por enquanto, participe por texto.</small>}</form>:data.enabled&&<form onSubmit={e=>{e.preventDefault();void action('join',{name:new FormData(e.currentTarget).get('name')});}}><label>Seu nome<input name="name" required maxLength={40} autoComplete="nickname"/></label><button className="button" disabled={busy}>Entrar no chat</button></form>}</>}
 </section>;
}