import { roleLabels } from '@/lib/admin/roles';
import { UserRowActions } from '@/components/admin/user-row-actions';
import Link from 'next/link';
import { requireOperations } from '@/lib/auth/operations';
import { managedUsers } from '@/server/services/admin-users';
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;role?:string;active?:string;page?:string}>}){
 const actor=await requireOperations(),p=await searchParams;const page=Math.max(1,Math.min(10000,Number(p.page)||1));const result=await managedUsers(p.q,p.role,p.active,Math.floor(page));
 const url=(n:number)=>`/admin/usuarios?${new URLSearchParams({q:p.q||'',role:p.role||'',active:p.active||'',page:String(n)})}`;
 return <><h1>Usuários</h1><Link className="button" href="/admin/usuarios/novo">+ Novo usuário</Link><form className="phase-filters"><label>Buscar nome/e-mail<input name="q" defaultValue={p.q} maxLength={120}/></label><label>Papel<select name="role" defaultValue={p.role}><option value="">Todos</option>{['OWNER','ADMIN','EDITOR'].map(r=><option key={r} value={r}>{roleLabels[r]}</option>)}</select></label><label>Status<select name="active" defaultValue={p.active}><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select></label><button className="button">Filtrar</button></form>
 <div className="table-scroll"><table><thead><tr>{['Nome','E-mail','Papel','Status','Último login','Criação','Ações'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{result.items.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{roleLabels[u.role]}</td><td>{u.active?'Ativo':'Inativo'}</td><td>{u.last_login_at?new Date(u.last_login_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Nunca'}</td><td>{new Date(u.created_at).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})}</td><td>{actor.role==='OWNER'||u.role!=='OWNER'?<UserRowActions id={u.id} name={u.name} active={u.active}/>:'Protegido'}</td></tr>)}</tbody></table></div><p>{result.total} usuários encontrados.</p><nav className="day-tabs">{page>1&&<Link href={url(page-1)}>Anterior</Link>}{page*30<result.total&&<Link href={url(page+1)}>Próxima</Link>}</nav></>;
}
